- README.md
> [RCL-156] Update readme link and install

- README.md
Adding a CRAN badge to the README.
> [RCL-164] add cran badge to readme

- R/civis_ml_workflows.R
- R/generate_client.R
- man/civis_ml_extra_trees_classifier.Rd
- man/civis_ml_extra_trees_regressor.Rd
- man/civis_ml_gradient_boosting_classifier.Rd
- man/civis_ml_gradient_boosting_regressor.Rd
- man/civis_ml_random_forest_classifier.Rd
- man/civis_ml_random_forest_regressor.Rd
- man/civis_ml_sparse_ridge_regressor.Rd
- man/generate_client.Rd
> [RCL-167] fix some spelling errors

- DESCRIPTION
I'm taking over
@jseabold, @keithing for vis
@wlattner for review/blessing
> change maintainer

- _pkgdown.yaml
- vignettes/civis_ml.Rmd
This PR fixes a few small doc issues brought up in #40.
> DOC: fixing typo in vignettes; adding functions to doc index

- R/io.R
- man/write_civis.Rd
Pretty straightforward PR - two lines of code (and I only wrote one of them)
Should be ready for review @patr1ckm!
> [RCL-190] Add if_exists = "drop" as parameter in write_civis

- CHANGELOG.md
- R/civis_ml.R
- man/civis_ml.Rd
Can you check this copy-paste job from [#440](https://github.com/civisanalytics/civis-python/pull/137/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e)?
@elsander
> [RCL-185] Document changes to civis_ml for civis_ml 2.0

- R/civis_ml.R
- man/civis_ml.Rd
- man/civis_ml_extra_trees_classifier.Rd
- man/civis_ml_extra_trees_regressor.Rd
- man/civis_ml_gradient_boosting_classifier.Rd
- man/civis_ml_gradient_boosting_regressor.Rd
- man/civis_ml_random_forest_classifier.Rd
- man/civis_ml_random_forest_regressor.Rd
- man/civis_ml_sparse_linear_regressor.Rd
- man/civis_ml_sparse_logistic.Rd
- man/civis_ml_sparse_ridge_regressor.Rd
- tests/testthat/test_civis_ml.R
This adds hyperband checks to `civis_ml`.
> [RCL-184] hyperband exceptions

- CHANGELOG.md
- R/reports.R
- man/publish_html.Rd
- man/publish_rmd.Rd
This PR just fixes a few small documentation errors that @patr1ckm noticed in #58.
> [RCL-198] Update Reports Documentation

- CHANGELOG.md
- DESCRIPTION
- R/civis_ml.R
- cran-comments.md
- man/civis_ml.Rd
- man/civis_ml_extra_trees_classifier.Rd
- man/civis_ml_extra_trees_regressor.Rd
- man/civis_ml_gradient_boosting_classifier.Rd
- man/civis_ml_gradient_boosting_regressor.Rd
- man/civis_ml_random_forest_classifier.Rd
- man/civis_ml_random_forest_regressor.Rd
- man/civis_ml_sparse_linear_regressor.Rd
- man/civis_ml_sparse_logistic.Rd
- man/civis_ml_sparse_ridge_regressor.Rd
- tests/testthat/test_io.R
- bump description and fix links
- mock file.size and rewrite multipart test to work on windows too
- spelling
- update CHANGELOG (this includes #71)
[windows results](https://win-builder.r-project.org/Sp5AFJ2F6On1/00check.log)
Closes #72
> civis-r 1.1.0 release

- CHANGELOG.md
- R/civis_ml.R
- man/CivisFuture.Rd
- man/civis_ml.Rd
- man/civis_ml_extra_trees_classifier.Rd
- man/civis_ml_extra_trees_regressor.Rd
- man/civis_ml_gradient_boosting_classifier.Rd
- man/civis_ml_gradient_boosting_regressor.Rd
- man/civis_ml_random_forest_classifier.Rd
- man/civis_ml_random_forest_regressor.Rd
- man/civis_ml_sparse_linear_regressor.Rd
- man/civis_ml_sparse_logistic.Rd
- man/civis_ml_sparse_ridge_regressor.Rd
This PR updates the `civis_ml` documentation with new features and defaults from CivisML 2.1.
> DOC update man pages with new CivisML features and defaults

- CHANGELOG.md
- R/io.R
- tests/testthat/test_io.R
> .numeric IO functions now fail for NA

- CHANGELOG.md
- R/io.R
- man/query_civis_file.Rd
- man/write_civis.Rd
- tests/testthat/test_io.R
It turns out that the `hidden` argument in write_civis hasn't worked for a while. This fixes that issue, and exposes the new `diststyle` argument in `imports_post`. 
Smoke tests pass.
> [RCL-205] hidden bug

- CHANGELOG.md
- R/civis_ml.R
- man/civis_ml.Rd
- vignettes/civis_ml.Rmd
This PR updates the CivisML stacking documentation with recent changes to the estimator structure.
> DOC update stacking documentation

- reference/CivisFuture.html
- reference/cancel.html
- reference/index.html
Since I missed a few things in the last release, here's an quick update to the docs.
Adds
- tables
- future methods
- query_civis_file
> doc update

- CHANGELOG.md
- R/zzz.R
> library(civis) works even if API key has expired

- CHANGELOG.md
- DESCRIPTION
> FIX: UTF-8 encoding

- CHANGELOG.md
> 1.5.1 Add date to changelog

- CHANGELOG.md
- DESCRIPTION
A pre-check is currently running on win-builder, I'll tag when this is ready to go.
I'm not planning on updating the default spec or static docs for this release.
> Release 1.6.0

- CHANGELOG.md
- R/reports.R
- R/tables.R
- cran-comments.md
- man/refresh_table.Rd
- man/transfer_table.Rd
- vignettes/civis_scripts.Rmd
- vignettes/concurrency.Rmd
- vignettes/data_import_and_export.Rmd
This should be what is necessary for release - cran comments, spell check.
> 2.0 release

- vignettes/civis_scripts.Rmd
Read it over after a month, and wanted to make some small changes
> Update civis_scripts vignette
