civisanalytics/civis-r

- README.md
We switched to travis-ci.org, updating the badge to match.
> [RCL-161] Use travis-ci.org badge

- README.md
- vignettes/quick_start.Rmd
This adds a very simple getting started guide which highlights a few `I/O` and `civis_ml` wrapper functions.
> [RCL-76] Adding a Quick Start vignette

- R/pagination_helpers.R
`purrr::as_function` was deprecated, using the suggested `purrr::as_mapper` instead.
> [RCL-160] update purrr::as_function

- R/io.R
- man/read_civis.Rd
- tests/testthat/test_io.R
This is adding behavior like [`civis-python`](https://github.com/civisanalytics/civis-python/blob/master/civis/io/_tables.py#L222) so users can catch the error raised when `read_civis` returns no rows.
> [RCL-138] Add condition for empty_result_error

- README.md
I missed `/articles` earlier when I updated the getting started guide!
> FIX: Fixing a bad link on the README

- R/await.R
- R/civis_ml.R
- R/client_base.R
- R/dbi-connection.R
- R/generate_client.R
- R/io.R
- R/reports.R
- tests/testthat/test-DBI.R
- tests/testthat/test_autogen.R
- tests/testthat/test_await.R
- tests/testthat/test_civis_ml.R
- tests/testthat/test_civis_ml_utils.R
- tests/testthat/test_client_base.R
- tests/testthat/test_fill_text_template.R
- tests/testthat/test_io.R
- tests/testthat/test_pagination.R
- tests/testthat/test_reports.R
- tests/testthat/test_utils.R
- tests/testthat/utils.R
- tools/generate_civis_ml_test_data.R
- tools/generate_default_client.R
- tools/integration_tests/smoke_test.R
- tools/run_generate_client.R
Some cleanup! Inspired because the new Rstudio 1.1.1 has a reasonable linter (cmd-option-shift-D).
I also found a small bug in `write_civis.character`.
@keithing or @wlattner this is probably a good PR to suggest other minor irritations that I can fix.
- `write_civis.character` now correctly reads default database.
- `test_reports publish_html` refactored to use mock
- tests now have all lower case names in `context`
- better respect of the 80 character
> [RCL-35] REF Linting

- R/io.R
- tests/testthat/test_io.R
We were incorrectly raising an error for `if_exists = "drop"` in `write_civis`, according to the api docs, we can pass "fail", "truncate", "append", or "drop".
@patr1ckm or @keithing for review.
> [RCL-165] Add drop as option for if_exists in write_civis

- vignettes/civis_ml.Rmd
It compiled in my master branch with `build_site()`, should work in the `gh-pages` branch also. The doc PR may have to be re-run?
> FIX: use package_file to find .rds models in vignette build

- R/io.R
- tests/testthat/test_io.R
Tables <2gb are read from memory, Tables >2gb are downloaded to a temporary file.
The total number of bytes in a textConnection is limited to 2^31-1, the maximum size of a string in R. This limit means that reading tables in `read_civis` straight from a `textConnection` is limited to tables of ~2gb.
`read_civis` now checks the size of the file before reading. Files larger than 2^31-1 bytes are downloaded to a temporary file. Files < 2^31-1 bytes are still read straight from a `textConnection`.
In addition, the following changes were made:
- If a query returns no results, this is now signalled in read_civis.sql and download_script_results (for download_civis)
- `stop_if_no_output` throws an error if a query produces no output.
- refactored tests for `read_civis` to more clearly delineate …
> [RCL-170] FIX: read_civis now checks file size before reading

- DESCRIPTION
- LICENSE
This fixes the following requests from CRAN maintainer:
```
Thanks, please omit the redundant "is an R package that helps analysts and developers" part. Rather add a webb reference in the form <http......> to the API.
License: BSD_3_clause + file LICENSE
We see:
License components with restrictions and base license permitting such:
BSD_3_clause + file LICENSE
File 'LICENSE':
Copyright (c) 2017, Civis Analytics
All rights reserved.
...
Please only use the CRAN template for the BSD_3_clause license as file LICENSE.
Please fix and resubmit.
```
[Here](https://cran.r-project.org/web/packages/splusTimeSeries/index.html) is an example of how `LICENSE` will work with the `BSD_3_clause` template.
> [RCL-66] FIX: Change LICENSE format, revise description

- DESCRIPTION
Should it be:
-  'Civis Data Science API'
- 'Civis' data science API
- 'Just publish the damn package'
@wlattner
> [RCL-66] One more round of description changes.

- CHANGELOG.md
- DESCRIPTION
- configure
- configure.win
- cran-comments.md
I think this will fix the [build issues](https://cran.r-project.org/web/checks/check_results_civis.html) on CRAN. 
On unix platforms, we use `bin/sh` instead of `bin/bash` as per [this footnote](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#FOOT24). `Rscript` is located through the use of the `R_HOME` environment variable temporarily created in `R CMD INSTALL`, as per the examples in the [configure docs](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Configure-and-cleanup). 
Windows uses uses the `ash` shell. Like in unix alikes, we use locate `R_HOME` to find `Rscript.exe` (also documented [here](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Configure-and-cleanup)).
I'm still working on replicating the environments these were created in. 
@keithing
> [RCL-174] fix build issues

- R/civis_ml.R
- man/civis_ml.Rd
- man/civis_ml_extra_trees_classifier.Rd
- man/civis_ml_extra_trees_regressor.Rd
- man/civis_ml_gradient_boosting_classifier.Rd
- man/civis_ml_gradient_boosting_regressor.Rd
- man/civis_ml_random_forest_classifier.Rd
- man/civis_ml_random_forest_regressor.Rd
- man/civis_ml_sparse_linear_regressor.Rd
- man/civis_ml_sparse_logistic.Rd
- man/civis_ml_sparse_ridge_regressor.Rd
- tests/testthat/test_civis_ml.R
This PR adds `validation_data` and `n_jobs` as arguments for training, and `cpu`, `memory`, and `disk_space` as arguments for prediction.
> ENH add new parameters to civis_ml training and prediction

- tests/testthat/test_civis_future.R
- tests/testthat/test_civis_ml.R
The only major change here is that we can't mock functions in `base` or `utils`. We can do so with minimal loss in test coverage.
@keithing for review
> [RCL-191] FIX: tests pass with new testthat

- .gitignore
- DESCRIPTION
- R/reports.R
- R/rstudio.R
- inst/rstudio/addins.dcf
- man/publish_rmd.Rd
- tests/testthat/test_reports.R
- tests/testthat/test_rstudio.R
This PR makes 2 changes:
1. `publish_rmd` now looks at the YAML of RMarkdown files for parameters.  This allows users to hard code parameters like `report_name` and `report_id` into the markdown file itself.  For example:
```
---
title: "RMarkdown Title"
civis:
report_name: "My Report Name"
report_id: 390232
---
RMarkdown text here ...
```
2.  This creates an RStudio addin "Publish to Civis" which will publish an RMarkdown file directly to a report a platform.  If `report_id` is hard coded in the YAML of the RMarkdown file, the same report will be updated, allowing users to easily change a report.
> [RCL-192] ENH: Adding an Rstudio Addin to publish RMD to platform

- CHANGELOG.md
- R/civis_future.R
- man/CivisFuture.Rd
- man/civis_platform.Rd
- tests/testthat/test_civis_future.R
- tests/testthat/test_civis_ml.R
`resolved` now polls the job from platform. This is useful in shiny apps, which can do polling for you without blocking. 
I also add error handling in the usual fashion, by just printing the log. 
```
fut <- future({ stop("asdf") })
value(fut)
```
Finally, I also fixed a test that was taking too long, dropping our test times to about ~10s from ~15s.
> [RCL-202] resolved future

- CHANGELOG.md
- R/civis_ml.R
- tests/testthat/test_civis_ml.R
CivisML no longer writes `metrics.json` files when validation is skipped. To handle this, I've added a `tryCatch` around reading in the metrics file.
I didn't add a test for this because my mock-fu isn't strong enough. I wanted to add a test with `must_fetch_output_json` mocked so that fetching `metrics.json` errored but not `model_info.json`. Any thoughts on how to test the new behavior, @patr1ckm? I did test manually and the fix works with an actual run from Platform.
> ENH tryCatch for missing metrics files

- README.md
I hear questions about `.Renviron` fairly frequently and think it's worth being explicit about. 
I clarified updating too. Using `install.packages` only installs (and triggers the updating) if the package has changed on CRAN. Users need to install from github directly in this case, which always triggers the update.
For contribution, I documented the special environment variable `R_CLIENT_DEV` as well as the contribution process.
Details:
- clarifies .Renviron creation when adding a key
- clarifies how to update the package with devtools
- reorders usage, focusing on the high level functions first
- adds more detail on the contribution process
@edakaceli does this address the `.Renviron` confusion? 
Fixes #90 .
> ENH update README

- CHANGELOG.md
- DESCRIPTION
- R/civis_ml.R
- man/civis_ml.Rd
CivisML v2.2 will include the ability for users to select a subset of targets from a multi-target model to write to the scoring table. If users only care about a subset of the model's outputs, they can save time and disk space by only keeping those predictions.
> ENH "dvs_to_predict" option for model predictions

- CHANGELOG.md
- R/civis_ml.R
- tests/testthat/test_civis_ml.R
In the python client, fetching CivisML models causes CivisML warnings to print to the screen, instead of keeping them buried in the metadata. This PR replicates that behavior in the R client.
Right now, I just have the warnings print without any annotation, even though they are Python warnings printing to an R console. If you think this needs to be clarified for the user, let me know.
> ENH print CivisML warnings when model results fetched

- CHANGELOG.md
- DESCRIPTION
- R/civis_ml.R
- tests/testthat/test_civis_ml.R
This PR adds feather support for newer versions of CivisML. This resolves a bug where users would pass local dataframes with factor-type columns, which in some cases would be written as integers in the csv, causing unexpected ETL behavior in CivisML (i.e., not categorically expanding factors).
The new behavior is as follows:
- for older versions of CivisML, there will be no change.
- for newer versions of CivisML (which support feather), the client will attempt to use feather for local dataframes by default. If the user does not have feather installed, it will fall back to csv, throwing an error if any columns are factors.
This feature matches Python client functionality: https://github.com/civisanalytics/civis-python/pull/200
> ENH add feather support for local dataframes being sent to CivisML

- README.md
Adds a few sentences about `.Renviron` for our windows users.
Fixes #96 .
> os specific install instructions

- R/io.R
- tests/testthat/test_io.R
As we dispatch `write_civis_file` based on `character`, there is some ambiguity. This adds a slightly better error to message to `write_civis_file` to help in this situation:
```R
x <- c("some chars", "to upload", "I'm not a filename.")
write_civis_file(x)
```
> Better error message for write_civis_file

- CHANGELOG.md
- R/generate_client.R
A test is running here:
https://platform.civisanalytics.com/#/scripts/containers/10601923
Since it passes loading the package, we should be good to go.
> FIX: remove linebreaks in parameter descriptions

- CHANGELOG.md
- R/civis_ml_utils.R
- tests/testthat/test_civis_ml.R
Use the newly-released v2.2 templates to run Civis Platform modeling jobs.
> ENH Update modeling to CivisML v2.2

- tests/testthat/test_civis_ml_plot.R
`ggplot2` version 2.3.0 now returns quosures for referring to variable names, breaking our tests (but not the code).
Instead of evaluating a quosure I just use the names in the data as given in the implementation. If the names of the data frame used in the implementation of the plotting methods change, the tests would need to change.  It's probably not worth making the tests robust to these changes.
Fixes #118
> TST fix tests for ggplot2.3

- R/civis_future.R
- _pkgdown.yaml
- man/CivisFuture.Rd
- man/cancel.Rd
This adds the table utilities and `CivisFuture` generics to the docs. I checked `NAMESPACE`, and this should be all that we are exporting (except for DBI).
Closes #117
> [DOC] Tables docs, CivisFuture generics, CivisML plots

- CHANGELOG.md
- R/io.R
- tests/testthat/test_io.R
This fixes the error from the ticket RCL-212, where Redshift sends out nulls. This may be a bug in `httr`, but in any case, I think it's better to just revert back to downloading redshift csv exports to a temporary file.
The ticket shows a reproducible example (that I won't repeat here for security reasons). On this branch, the call to `read_civis` now works just like `download_civis` would, reading in a data frame with hundreds of rows and the following warnings:
```
Warning messages:
1: In read.table(file = file, header = header, sep = sep, quote = quote,  :
line 2 appears to contain embedded nulls
2: In read.table(file = file, header = header, sep = sep, quote = quote,  :
line 3 appears to contain embedded nulls
3: In read.table(file = file, header = header, sep = sep, quote = quote, …
```
> [RCL-212] FIX: read_civis does not read from textConnections

- CHANGELOG.md
- R/io.R
- tests/testthat/test_io.R
I've been noticing an above average number of upload failures in my jobs in `write_civis_file`. This should help the client be more robust by default.
I was initially concerned about automatically retrying on `POST`, but retries are best practice according to [the docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/ErrorBestPractices.html) and also happen in [the python client](https://github.com/civisanalytics/civis-python/blob/master/civis/io/_files.py#L100). 
Additionally, should a `POST` successfully complete multiple times, the end result would be that the file is just uploaded multiple times with the last upload overwriting anything previous. It only wastes network bandwidth and does not result in any data corruption.
> [RCL-106] Retry uploads in write_civis_file

- CHANGELOG.md
- R/civis_ml.R
We tried to be helpful and fail early with a helpful error message for models where hyperband isn't supported. Since hyperband is now supported for `stacking` estimators, we can remove the error.
Is multi-output still not supported for these?
c("sparse_linear_regressor", "sparse_ridge_regressor",
"gradient_boosting_regressor",
"sparse_logistic", "gradient_boosting_classifier")
Fixes #131
> FIX: hyperband now supported with stacking

- CHANGELOG.md
- R/generate_client.R
- tests/testthat/test_autogen.R
This forces verb names in API calls to be upper case. The only changes are in the first commit, the second commit is regenerating the default specification for testing.
Fixes #153.
> Make verb names in API calls upper case

- DESCRIPTION
- R/await.R
- man/CivisFuture.Rd
- tests/testthat/test_await.R
Fixes #147 ENH: `await_all` should be vectorized over two arguments
Does not pass existing tests, submitting what I have so far for any feedback.  Replacing lapply() with mapply() seems to have broken something.
> Partial: Adding second argument to `await_all`

- CHANGELOG.md
- R/civis_future.R
Small change, long story.
The integration tests were failing in `plan(civis_platform)` because they were on R latest. 
The break happened because the serialization format is changing in R 3.6.0, so any `.rds` files generated by R 3.6.0 require at least R 3.5.0 to read. This failed in the `future` test where the `.rds` we upload to platform was generated by R 3.6.0 but read by an older R version prior to R 3.5.0 (e.g. R 3.4.3).
We have R 3.5.2 in datascience-r 2.8.0, so I can just bump the image to fix. I'm tagging the docker image for `plan(civis_platform)` to `2` to decrease errors of this kind in the future.
> FIX: serialization compatibility on R 3.6.0

- CHANGELOG.md
- R/await.R
- man/CivisFuture.Rd
- man/await.Rd
- tests/testthat/test_await.R
Here's a fix for `await_all`. It is now vectorized over two arguments, and still works if only given `.x`. `call_once` was refactored to remove an unnecessary `.id` parameter.
```
ids <- c(23820523, 23820523)
runs <- c(130390319, 130390319)
await_all(scripts_get_r_runs, .x = ids, .y = runs)
await_all(scripts_get_r_runs, .x = ids, .y = runs, .success_states = 'asdf', .timeout = 1)
await_all(scripts_get_r_runs, .x = ids, .y = runs, .success_states = 'asdf', .verbose = TRUE, .timeout=2)
```
Fixes #171 . @Zephyraith thanks for the 30% WIP to get this started!
> await_all 2

- CHANGELOG.md
- R/scripts.R
- man/run_template.Rd
- tests/testthat/test_scripts.R
Modified run_template() so that if specified, the JSON values are returned instead of the associated file ids
> [SERD-1445] return JSON from run template

- CHANGELOG.md
- R/client_base.R
- tests/testthat/test_client_base.R
This increases default retrying for `call_api`. Changes:
- When rate limiting, all verbs can be safely retried. Fixes #201 .
- Increase the default retries to 10, with maximum wait time for 1 hour. Fixes #210 .
- Fix assumption in error handling that an `errorDescription` field is provided in the response (it isn't for at least 429). Fixes #213 .
The smoke tests successfully ran locally.
Do you mind one last civis-r code review @keithing ?
> More retries on rate-limiting

- CHANGELOG.md
- R/utils.R
- tests/testthat/test_utils.R
This bug popped up in office hours, and just wanted to fix.
Context: checking whether a provided database is equal to another with `identical` requires that the classes of the two objects are the same. However, if a string has been interpolated with e.g. `str_glue`, `identical` fails because the classes aren't the same:
```
class(str_glue('a'))
[1] "glue"      "character"
identical(str_glue('a'), 'a')
[1] FALSE
```
Checking that the values are the same (not the objects) fixes the bug.
Thanks @lmalkovich for the report!
> FIX: The `database` parameter in `read_civis` now works with glue

- DESCRIPTION
- README.md
This is just to try to have consistency with naming elsewhere, particularly with the Python client.
Related: https://github.com/civisanalytics/civis-python/pull/352
> replace Civis data science API with Civis Platform API

- CHANGELOG.md
- vignettes/civis_ml.Rmd
The documentation for the CivisML version implies that the major use of the civisml_version parameter (added in #224) is to use an older version of CivisML, which seems slightly misleading (for clarity, this original language came from my changes at https://github.com/civisanalytics/civis-python/pull/341, not Sahil's -- my bad). I'm updating the docs to clarify that it's about pinning the version for production work as a more probable use case.
The parallel PR for civis-python is https://github.com/civisanalytics/civis-python/pull/358
> [PARO-741] DOC update language for CivisML version

- CHANGELOG.md
- DESCRIPTION
Adds a website link to the DESCRIPTION file. The change to the page title already happened in a PR about a month ago (#222), so no changes to make there. Closes #184.
> DOC add website link to description file

- DESCRIPTION
Unfortunately this is covered in writing R extensions. I assume that the package will get rejected with a bot/mailing list listed as a maintainer.
> The mandatory ‘Maintainer’ field should give a single name followed by a valid (RFC 2822) email address in angle brackets. It should not end in a period or comma. This field is what is reported by the maintainer function and used by bug.report. For a CRAN package it should be a person, not a mailing list and not a corporate entity: do ensure that it is valid and will remain valid for the lifetime of the package.
> Note that the display name (the part before the address in angle brackets) should be enclosed in double quotes if it contains non-alphanumeric characters such as comma or period. (The current standard, RFC 5322, allows periods but …
> Maintainer must be a person

- R/civis_ml_utils.R
- tests/testthat/test_io.R
- tools/integration_tests/smoke_test.R
After the `stringsAsFactors` default change in R-devel, there are two errors in the package that caused `R CMD CHECK` failures:
https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/civis-00check.html
I decided to preserve `stringsAsFactors=TRUE`  when returning feature importances, since the package  originally returned feature importances as a data frame with factors.
The breaking test for `write_civis_file` highlights that this breaking change in R may affect users downstream. For example, calls to `read_civis` with default arguments will now return data frames from `read.csv` where `stringsAsFactors=FALSE`. 
We could insulate our users from this change by specifying `stringsAsFactors=TRUE` in `read_civis` calls as the  default. However, I don't feel that it is our …
> FIX: stringsAsFactors

- CHANGELOG.md
- R/io.R
- tests/testthat/test_client_base.R
- tests/testthat/test_io.R
In this PR, I'd like to propose swapping out calls to `httr::POST()` etc. with `httr::RETRY()`.  It looks like you're already using `RETRY()` in a lot of places, which is awesome! This PR just changes the few remaining places where you weren't.
This will make the package more resilient to transient problems like brief network outages or periods where the service(s) it hits are overwhelmed. In my experience, using retry logic almost always improves the user experience with HTTP clients.
I also noticed that you are mocking `httr::VERB()` but that it's never called in the code, so I removed those mocks.
I'm working on https://github.com/chircollab/chircollab20/issues/1 as part of Chicago R Collab, an R 'unconference' in Chicago.
Thanks for your time and consideration!
> replaced single-shot HTTP requests with RETRY logic

- tools/integration_tests/smoke_test.R
This specifies the docker image+tag for the futures used in the smoke test.  The default image+tag for futures is datascience-r:3, but we want the smoke test and the futures it creates to run on the latest code.
> specify docker tags in futures created by the smoke test

- tools/integration_tests/smoke_test.R
This fixes/relaxes a test that had hardcoded an assumption about an old redshift cluster config.
> fix smoke test by relaxing expected file count from multifile unload

- CHANGELOG.md
- DESCRIPTION
- R/civis_future.R
- man/CIVIS_ML_CLASSIFIERS.Rd
- man/CIVIS_ML_REGRESSORS.Rd
- man/CivisFuture.Rd
- tests/testthat/test_io.R
- tools/integration_tests/smoke_test.R
This fixes the failing smoke test, replacing the test with something simpler. 
The default `CivisFuture` image tag is now also latest, since `datascience-r` will be bumping a major version for an R 4.0.0 release.
> [APIC-297] Fix smoke test; update CivisFuture default docker image tag

- CHANGELOG.md
- R/generate_client.R
Incidentally, this also fixes doc bugs for a few other endpoints (noted in the changelog).
I regenerated the docs locally for testing, here are the results:
`databaseTable` and `storagePath` lists were not documented previously.
I will update the client/docs in the 3.0.0 release PR.
Fixes #220.
> FIX cass/ncoa doc param

- DESCRIPTION
- R/pagination_helpers.R
The `fetch_all` function is intended to call `fetch_until` until a result of `FALSE` is returned. However, when the API returns no result, that output manifests as a NULL, not a boolean `FALSE` value. This change prevents a coercion error of trying to boolean compare a NULL value in R.
> Patch fetch_all pagination helper

- DESCRIPTION
- NEWS.md
- R/civis_future.R
- tests/testthat/test_civis_future.R
New versions of `future` (> 1.31.0) will no longer recognize "succeeded" as a resolved state. This PR sets `future$state` to "finished" if the API job has a "succeeded" status.
See also Issue #245
> Set future$state to "finished" if API call "succeeded"

- .gitignore
- .travis.yml
- NEWS.md
- R/client_base.R
- R/io.R
- R/reports.R
- tests/testthat/test_civis_future.R
- tests/testthat/test_civis_ml.R
- tests/testthat/test_civis_ml_utils.R
- tests/testthat/test_civis_ml_workflows.R
- tests/testthat/test_client_base.R
- tests/testthat/test_io.R
- tests/testthat/test_logs.R
- tests/testthat/test_reports.R
- tests/testthat/test_rstudio.R
- tests/testthat/test_scripts.R
- tests/testthat/test_tables.R
- tests/testthat/test_utils.R
- tests/testthat/utils.R
- tools/install-and-run-tests.R
This replaces [`with_mock()`](https://testthat.r-lib.org/reference/with_mock.html) with [`local_mocked_bindings()`](https://testthat.r-lib.org/reference/local_mocked_bindings.html) since the former is deprecated and won't be available in R 4.5. See #254.
> Replace `with_mock` with `local_mocked_bindings` in the tests
